export const ERRORS = {
  STATE_NOT_FOUND: "State não encontrado",
  USER_NOT_CONNECTED: "Nenhum usuário conectado",
  EMAIL_NOT_SENT: "Ocorreu um erro ao enviar o email",
  EMAIL_INVALID: "Email inválido",
  EMAIL_REQUIRED: "Email é obrigatório",
  EMAIL_ALREADY_VERIFIED: "Email já verificado",
  EMAIL_ALREADY_IN_USE: "Email já utilizado",
  GOOGLE_REVOKE_TOKEN: "Falha ao revogar token Google",
  GOOGLE_ACCOUNT_ALREADY_LINKED: "Esta conta Google já está vinculada.",
  SPOTIFY_ACCOUNT_ALREADY_LINKED: "Esta conta Spotify já está vinculada.",
  INVALID_TOKEN: "Token expirado/inválido",
  REAUTH_TOKEN: "Erro ao reautenticar tokens",
  SYNC_PLAYLIST: "Erro ao sincronizar playlist",
  SERVICE_CONNECTIONS_NOT_ACTIVE: "Conexão com serviços necessário não estão ativas",
  SERVICE_CONNECTION_INVALID: "Serviço de conexão não identificado/suportado",
  SERVICE_CONNECTION_NOT_FOUND: "Conexão não encontrada",
  RESET_PASSWORD: "O código, e-mail ou senha estão inválidos ou expirados.",
  SET_PASSWORD_USER_HAS_PASSWORD: "Caso tenha esquecido a senha, vá para o formulário de esqueci minha senha",
  INVALID_CREDENTIALS: "Email ou senha inválidos",
  UNATHORIZED_OPERATION: "Operação não permitida",
  OAUTH_INVALID_METHOD: "Metodo inválido/suportado",
  OAUTH_USER_ALREADY_EXISTIS: "Já existe um usuário cadastrado com esses dados. Faça login e conecte o serviço",
  OAUTH_USER_NOT_FOUND: "Nenhum usuário encontrado, faça o registro",
  OAUTH_INVALID_CREDENTIALS: "Não foi possível obter/verificar o email/nome.",
  OAUTH_CONNECT_USER_INVALID: "Usuário não identificado para conexão.",
  OAUTH_CONNECT_USER_NOT_FOUND: "Nenhum usuário encontrado, conta do serviço diferente da cadastrada",
  TOKEN_SERIALIZER_ERROR: "Erro ao deserializar o Token",
  TOKEN_SERIALIZER_INVALID: "Token encriptado inválido",
  TOKEN_EXCHANGE_ERROR: "Erro ao fazer a troca de tokens com o serviço",
  PLAYLIST_NOT_FOUND: "Playlist não encontrada/inválida"
} as const;